/// DO NOT EDIT THIS FILE
/// THIS FILE NEEDED FOR ANNOTATE THE METHOD INSIDE THE REPOSITORY
/// USING THE ANNOTATIONS `BRICK_HOUSE` COULD IDENTIFY THE METHOD USED
/// BRICK_HOUSE GENERATE APK WILL DELETE THIS FILE FOR YOU OR DELETE IT MANUALLY

abstract class HttpAnnotations {
  final String endPoint;

  const HttpAnnotations({required this.endPoint});
}

class GET extends HttpAnnotations {
  const GET({required super.endPoint});
}

class POST extends HttpAnnotations {
  const POST({required super.endPoint});
}

class PATCH extends HttpAnnotations {
  const PATCH({required super.endPoint});
}

class DELETE extends HttpAnnotations {
  const DELETE({required super.endPoint});
}

class PUT extends HttpAnnotations {
  const PUT({required super.endPoint});
}
