name: test_enc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  hive: ^2.2.3
  http: ^1.2.0
  hydrated_bloc: ^9.1.4
  injectable: ^2.3.2
  path_provider: ^2.1.2
dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env.development
    - .env.production
flutter_gen:
  output: lib/core/gen/
  line_length: 80
  integrations:
    flutter_svg: true
